s= "Tops Technologies"

print(len(s))
print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.swapcase())
print("python programming".title())
print(s.center(80,"*"))
print(s.count("T"))
print(s.endswith ("es"))
print(s.startswith("To"))
print(s.find("log"))
print(s.index("e"))
print("tops123".isalnum())
print("tops".isalnum())
print(s.istitle())
print("Hello".replace("l","w"))
